#!/usr/bin/env bash
# Install and enable a systemd system service to run the Smart Air web app on boot (headless).
# Project path is detected from the repo root. Run on the Pi with sudo.
#
#   sudo ./scripts/install-smartair-service.sh
#
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${1:-$ROOT/.client-demo.env}"
UNIT="smartair-web.service"
DEST="/etc/systemd/system/${UNIT}"

if [[ $(id -u) -ne 0 ]]; then
  echo "Run with: sudo $0" >&2
  exit 1
fi
if [[ ! -f "$ROOT/run" ]]; then
  echo "Expected repo at $ROOT (with ./run). Run from the smartairchecker clone on the Pi." >&2
  exit 1
fi
if [[ -f "$ENV_FILE" ]]; then
  # shellcheck source=/dev/null
  set -a
  source "$ENV_FILE" 2>/dev/null || true
  set +a
fi
U="${CLIENT_DEMO_USER:-${SUDO_USER:-pi}}"
if ! id -u "$U" &>/dev/null; then
  echo "User $U does not exist. Set CLIENT_DEMO_USER in $ENV_FILE" >&2
  exit 1
fi
UGROUP="$(id -gn "$U")"
SUPP=""
for g in gpio i2c; do
  if getent group "$g" &>/dev/null; then
    SUPP="${SUPP}${SUPP:+,}$g"
  fi
done
RUN_ABS="$ROOT/run"
if [[ ! -x "$RUN_ABS" ]]; then
  echo "Make sure $RUN_ABS is executable: chmod +x $RUN_ABS" >&2
  exit 1
fi
# Assumes the project path has no spaces (typical for /home/pi/…)
cat >"$DEST" <<EOF
# Generated by $0 — re-run the installer to change paths or user.
[Unit]
Description=Smart Air Checker web (headless)
After=network-online.target
Wants=network-online.target
[Service]
Type=simple
User=$U
Group=$UGROUP
WorkingDirectory=$ROOT
Environment=PYTHONPATH=$ROOT
EOF
if [[ -n "$SUPP" ]]; then
  echo "SupplementaryGroups=$SUPP" >>"$DEST"
fi
cat >>"$DEST" <<EOF
ExecStart=$RUN_ABS
Restart=on-failure
RestartSec=20
ExecStartPre=/bin/sleep 5
[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable "$UNIT"
echo "[install-smartair-service] Installed and enabled: $UNIT"
echo "  User=$U  WorkingDirectory=$ROOT"
echo "  Start now:  sudo systemctl start $UNIT"
echo "  Status:     sudo systemctl status $UNIT"
echo "  Logs:       journalctl -u $UNIT -f"
exit 0
