#!/usr/bin/env bash
# Install and enable a systemd system service to run the Smart Air web app on boot (headless).
# Project path is detected from the repo root. Run on the Pi with sudo.
#
#   sudo ./scripts/install-smartair-service.sh
#
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${1:-$ROOT/.client-demo.env}"
UNIT="smartair-web.service"
DEST="/etc/systemd/system/${UNIT}"

if [[ $(id -u) -ne 0 ]]; then
  echo "Run with: sudo $0" >&2
  exit 1
fi
if [[ ! -f "$ROOT/run" ]]; then
  echo "Expected repo at $ROOT (with ./run). Run from the smartairchecker clone on the Pi." >&2
  exit 1
fi
if [[ -f "$ENV_FILE" ]]; then
  # shellcheck source=/dev/null
  set -a
  source "$ENV_FILE" 2>/dev/null || true
  set +a
fi
# Do not require "pi" — many images use a different first user; .client-demo.env may still say pi.
U=""
if [[ -n "${CLIENT_DEMO_USER:-}" ]] && id -u "$CLIENT_DEMO_USER" &>/dev/null; then
  U="$CLIENT_DEMO_USER"
fi
if [[ -z "$U" && -n "${SUDO_USER:-}" ]] && id -u "$SUDO_USER" &>/dev/null; then
  U="$SUDO_USER"
fi
if [[ -z "$U" ]]; then
  U="$(getent passwd 2>/dev/null | awk -F: '$3==1000{print $1; exit}')"
fi
if [[ -z "$U" ]]; then
  echo "Could not find a valid login user for the systemd service." >&2
  echo "On the Pi, as the user who owns this project, run:  whoami" >&2
  echo "Put that in $ENV_FILE:  CLIENT_DEMO_USER=<name>" >&2
  echo "Then:  sudo $0" >&2
  exit 1
fi
if ! id -u "$U" &>/dev/null; then
  echo "User $U is not valid. Set CLIENT_DEMO_USER in $ENV_FILE to the output of:  whoami" >&2
  exit 1
fi
if [[ -n "${CLIENT_DEMO_USER:-}" ]] && ! id -u "$CLIENT_DEMO_USER" &>/dev/null; then
  echo "[install-smartair-service] Note: CLIENT_DEMO_USER=$CLIENT_DEMO_USER does not exist — using $U. Set CLIENT_DEMO_USER=$U in $ENV_FILE" >&2
fi
UGROUP="$(id -gn "$U")"
SUPP=""
for g in gpio i2c; do
  if getent group "$g" &>/dev/null; then
    SUPP="${SUPP}${SUPP:+,}$g"
  fi
done
RUN_ABS="$ROOT/run"
if [[ ! -x "$RUN_ABS" ]]; then
  echo "Make sure $RUN_ABS is executable: chmod +x $RUN_ABS" >&2
  exit 1
fi
VPY="$ROOT/.venv/bin/python3"
if [[ ! -x "$VPY" ]]; then
  echo "" >&2
  echo "smartair-web.service needs a project virtualenv. systemd will run ./run as user $U," >&2
  echo "but first-time bootstrap (apt/pip) often fails in the background with no TTY." >&2
  echo "Fix: as that user, create the venv once, then re-run this script:" >&2
  echo "  sudo -u $U -H bash -lc 'cd $ROOT && ./pi-bootstrap.sh'" >&2
  echo "  sudo $0 $ENV_FILE" >&2
  echo "" >&2
  exit 1
fi
# Assumes the project path has no spaces (typical for /home/pi/…)
cat >"$DEST" <<EOF
# Generated by $0 — re-run the installer to change paths or user.
[Unit]
Description=Smart Air Checker web (headless)
After=network-online.target
Wants=network-online.target
[Service]
Type=simple
User=$U
Group=$UGROUP
WorkingDirectory=$ROOT
Environment=PYTHONPATH=$ROOT
Environment=PYTHONUNBUFFERED=1
EOF
if [[ -n "$SUPP" ]]; then
  echo "SupplementaryGroups=$SUPP" >>"$DEST"
fi
# ExecStart = venv + absolute run.py; WorkingDirectory=ROOT. No ExecStartPre (sleep looked
# like a failure in journalctl, but the real error is the Python line below in logs).
cat >>"$DEST" <<EOF
ExecStart=$VPY $ROOT/run.py
Restart=on-failure
RestartSec=20
[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable "$UNIT"
echo "[install-smartair-service] Installed and enabled: $UNIT"
echo "  User=$U  WorkingDirectory=$ROOT"
echo "  Start now:  sudo systemctl start $UNIT"
echo "  Status:     sudo systemctl status $UNIT"
echo "  Logs:       journalctl -u $UNIT -f"
exit 0
